#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, in7,    leftLineTracker, sensorLineFollower)
#pragma config(Sensor, in8,    rightLineTracker, sensorLineFollower)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Science Fair Maze Code

#include "includes.h"

task main()
{
	startTask(driveTask);
	disableDriveTask();

	// initialization function for the pathfinding code
	init();

	bool pathfindingMode = false;
	while (true) {

		if (pincerCloseButton()) {
			disableDriveTask();
			driveOneTile();
			//turnLeft();
			//turnRight();
		}

		checkAndMoveSimplified();

		if (breakBool) {
			break;
		}
		wait1Msec(10);
	}

}
