#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Science Fair Maze Code

#include "includes.h"

task main()
{
	startTask(driveTask);
	// HAVE TO DISABLE DRIVE TASK TO LET PATHFINDER DO ITS THING
	enableDriveTask();
	disableDriveTask();

	while (true) {

		/*if (pincerCloseButton()) {
			disableDriveTask();
			driveForwardInches(100, 30, 5000, APPLY_BRAKE);
			enableDriveTask();
		}*/

		checkAndMoveSimplified();
		if (breakBool) {
			break;
		}
		wait1Msec(10);
	}

}
